# Generated by Django 3.2.2 on 2021-05-08 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='b_date',
        ),
        migrations.AddField(
            model_name='board',
            name='b_created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='b_created_date', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='b_updated_date',
            field=models.DateTimeField(auto_now=True, db_column='b_updated_date'),
        ),
    ]
